#      _   _           _     _____  _             _                #
#     | \ | |         | |   |  __ \| |           (_)               #
#     |  \| | _____  _| |_  | |__) | |_   _  __ _ _ _ __  ___      #
#     | . ` |/ _ \ \/ / __| |  ___/| | | | |/ _` | | '_ \/ __|     #
#     | |\  |  __/>  <| |_  | |    | | |_| | (_| | | | | \__ \     #
#     |_| \_|\___/_/\_\\__| |_|    |_|\__,_|\__, |_|_| |_|___/     #
#                                           __/ |                  #
#                                          |___/                   #
#                       Servidor de Suporte                        #
#               https://nextplugins.com.br/discord                 #

database:
  version: '2.1.0'
  type: 'sqlite' # Opções válidas: 'sqlite' e 'mysql'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'

plugin:
  configuration:
    # Habilitar backups quando servidor reinicia
    autobackup: false
    # Método de salvamento de contas
    # true - Modo de NICK - Salvar a conta pelo nick do jogador (Recomendado para servidores piratas)
    # false - Modo de UUID - Salvar a conta pelo id único do jogador (Recomendado para servidores originais)
    # Caso efetue a mudança:
    # Se você utiliza SQLITE, apague o arquivo database.db da pasta database
    # Se você utiliza MYSQL, utilize a função DROP na table nexteconomy_data
    nick-save-method: true
    # Sistema de bolsa de valores
    # Valor inicial
    # Quando um jogador entra no servidor, começa com essa quantia
    initial-balance: 1500
    # Dinheiro mínimo necessário para enviar a um jogador
    # Evitar flodarem /money pay <jogador> 1
    min-value: 1000000
    # Sistema de cheques
    check:
      # ative ou desative o sistema de cheque
      enable: true
      # valor mínimo para criar um cheque
      min-value: 1000000
      # item que irá simbolizar um cheque
      item:
        display-name: '&aCheque de coins'
        material: PAPER
        data: 0
        lore:
          - ''
          - '&7Quantia armazenada:&f $amount'
          - ''
          - '&aClique esquerdo para resgatar.'

file-version: 1
